parameters:
#    glutzic_github_wrike.example.class: Glutzic\GithubWrikeBundle\Example

services:
#    glutzic_github_wrike.example:
#        class: %glutzic_github_wrike.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
